export const navLinks = [{
        id: 1,
        name: 'Home',
        href: '#home',
    },
    {
        id: 2,
        name: 'About',
        href: '#about',
    },
    {
        id: 3,
        name: 'Work',
        href: '#work',
    },
    {
        id: 4,
        name: 'Contact',
        href: '#contact',
    },
];

export const clientReviews = [{
        id: 1,
        name: 'AbdulBait Adesiji',
        position: 'User Experience Designer | Product Designer | UX Researcher',
        img: 'assets/Screenshot_20241125-100937.png',
        review: 'A great team player, contributed to the front end development project of our team presentation at the google solution challenge 2022. Humble and passionate about solving real life problems ',
    },
    // {
    //     id: 2,
    //     name: 'Ernest Henry Wilson ',
    //     position: 'Founder of Regal flowers',
    //     img: 'assets/review2.png',
    //     review: 'Adrian’s expertise in web development is truly impressive. He delivered a robust and scalable solution for our e-commerce site, and our online sales have significantly increased since the launch. He’s a true professional! Fantastic work.',
    // },
];

export const myProjects = [
    {
        title: 'RegaL Flowers - Ecommerce Platfrom',
        desc: "Nigeria's most loved online flower shop with same day delivery in Lagos and Abuja",
        subdesc: 'Built as a unique Ecommerce app with Next.js 14,Node.js,Mongo DB,Firebase,stripe, Tailwind CSS, TypeScript, Framer Motion and Convex, Regal flowers is designed for optimal performance and scalability.',
        href: 'https://www.regalflowers.com.ng/?gad_source=1&gclid=Cj0KCQiAuou6BhDhARIsAIfgrn5xgpfibzaJCwcH0IG4vplm_AaxX6aaEAyypCN-U7tKP-y_f29cziMaAvUpEALw_wcB#contactSection',
        texture: '/textures/project/Regal Flowers _ Same Day Flower Delivery Shop in Lagos and Abuja, Nigeria - Google Chrome 2024-11-25 09-01-26.mp4',
        logo: '/assets/project-logo1.png',
        logoStyle: {
            backgroundColor: '#2A1816',
            border: '0.2px solid #36201D',
            boxShadow: '0px 0px 60px 0px #AA3C304D',
        },
        spotlight: '/assets/spotlight1.png',
        tags: [{
                id: 1,
                name: 'React.js',
                path: '/assets/react.svg',
            },
            {
                id: 2,
                name: 'TailwindCSS',
                path: 'assets/tailwindcss.png',
            },
            {
                id: 3,
                name: 'TypeScript',
                path: '/assets/typescript.png',
            },
            {
                id: 4,
                name: 'Framer Motion',
                path: '/assets/framer.png',
            },
        ],
    },
    {
        title: 'MedHealthCatalyst - Health Management System',
        desc: 'An innovative healthcare platform designed to streamline essential medical processes. It simplifies patient registration, appointment scheduling, and medical record management, providing a seamless experience for both healthcare providers and patients.',
        subdesc: 'With a focus on efficiency, MedHealthCatalyst integrantes complex forms and SMS notifications, by using Next.js,Nodejs, Appwrite, Twillio and Sentry that enhance operational workflows.',
        href: 'https://med-health-catalyst-bpd5.vercel.app/',
        texture: '/textures/project/MedHealthCatalyst - Google Chrome 2024-11-25 08-37-26.mp4',
        logo: '/assets/project-logo3.png',
        logoStyle: {
            backgroundColor: '#60f5a1',
            background: 'linear-gradient(0deg, #60F5A150, #60F5A150), linear-gradient(180deg, rgba(255, 255, 255, 0.9) 0%, rgba(208, 213, 221, 0.8) 100%)',
            border: '0.2px solid rgba(208, 213, 221, 1)',
            boxShadow: '0px 0px 60px 0px rgba(35, 131, 96, 0.3)',
        },
        spotlight: '/assets/spotlight3.png',
        tags: [{
                id: 1,
                name: 'React.js',
                path: '/assets/react.svg',
            },
            {
                id: 2,
                name: 'TailwindCSS',
                path: 'assets/tailwindcss.png',
            },
            {
                id: 3,
                name: 'TypeScript',
                path: '/assets/typescript.png',
            },
            {
                id: 4,
                name: 'Framer Motion',
                path: '/assets/framer.png',
            },
        ],
    },
    {
        title: 'Connectinskillz - Online Learning Platform',
        desc: 'Connectinskillz is a comprehensive online learning platform that offers users a centralized learning system management dashboard. It allows users to connect with their mentors, submit assignment, schedule meeting, and connect with students of like minds.',
        subdesc: 'Built with Next.js 14, Connectinskillz ensures a smooth and secure learning experience, tailored to meet the needs of modern consumers.',
        href: 'https://www.connectinskillz.org/',
        texture: '/textures/project/Home _ ConnectinSkillz - Google Chrome 2024-11-25 09-17-39.mp4',
        logo: '/assets/project-logo4.png',
        logoStyle: {
            backgroundColor: '#0E1F38',
            border: '0.2px solid #0E2D58',
            boxShadow: '0px 0px 60px 0px #2F67B64D',
        },
        spotlight: '/assets/spotlight4.png',
        tags: [{
                id: 1,
                name: 'React.js',
                path: '/assets/react.svg',
            },
            {
                id: 2,
                name: 'TailwindCSS',
                path: 'assets/tailwindcss.png',
            },
            {
                id: 3,
                name: 'TypeScript',
                path: '/assets/typescript.png',
            },
            {
                id: 4,
                name: 'Framer Motion',
                path: '/assets/framer.png',
            },
        ],
    },
    {
        title: 'Muni - AI Banking App',
        desc: 'Muni is a groundbreaking Software-as-a-Service application that empowers users to monitor all their assets in a single app using AI technology. With features like AI-driven image editing, a payments system, and a credits-based model.',
        subdesc: 'Built with Next.js 14, Cloudinary AI, Muni combines cutting-edge technology with a user-centric approach. It can be turned into a side income or even a full-fledged business.',
        href: 'https://munii.finance/',
        texture: '/textures/project/Munii Finance - Revolutionize Your Personal Finance Management - Google Chrome 2025-08-16 18-23-18.mp4',
        logo: '/assets/project-logo5.png',
        logoStyle: {
            backgroundColor: '#1C1A43',
            border: '0.2px solid #252262',
            boxShadow: '0px 0px 60px 0px #635BFF4D',
        },
        spotlight: '/assets/spotlight5.png',
        tags: [{
                id: 1,
                name: 'React.js',
                path: '/assets/react.svg',
            },
            {
                id: 2,
                name: 'TailwindCSS',
                path: 'assets/tailwindcss.png',
            },
            {
                id: 3,
                name: 'TypeScript',
                path: '/assets/typescript.png',
            },
            {
                id: 4,
                name: 'Framer Motion',
                path: '/assets/framer.png',
            },
        ],
    },
    {
        title: 'Tweakrr',
        desc: 'Tweakrr automatically handles your in-text citations and reference lists. You write the brilliance, well handle the boring bits.',
        subdesc: 'Built with Next.js 14,  Tweakrr combines cutting-edge technology with a user-centric approach. It can be turned into a side income or even a full-fledged business.',
        href: 'https://www.tweakrr.com/',
        texture: '/textures/project/Tweakrr - Google Chrome 2025-08-16 18-29-16.mp4',
        logo: '/assets/project-logo5.png',
        logoStyle: {
            backgroundColor: '#1C1A43',
            border: '0.2px solid #252262',
            boxShadow: '0px 0px 60px 0px #635BFF4D',
        },
        spotlight: '/assets/spotlight5.png',
        tags: [{
                id: 1,
                name: 'React.js',
                path: '/assets/react.svg',
            },
            {
                id: 2,
                name: 'TailwindCSS',
                path: 'assets/tailwindcss.png',
            },
            {
                id: 3,
                name: 'TypeScript',
                path: '/assets/typescript.png',
            },
            {
                id: 4,
                name: 'Framer Motion',
                path: '/assets/framer.png',
            },
        ],
    },
    {
        title: 'Rekrutklin',
        desc: 'Rekrutklin is a revolutionary job matching platform that connects employers with top talent. Our AI-powered system ensures the best fit for both parties.',
        subdesc: 'Built with Next.js 14 and Nodejs,  Rekrutklin combines cutting-edge technology with a user-centric approach. It can be turned into a side income or even a full-fledged business.',
        href: 'https://rekrutklin.com/',
        texture: '/textures/project/rekrutklin - Google Chrome 2026-04-05 08-55-08.mp4',
        logo: '/assets/LOGO.svg',
        logoStyle: {
            backgroundColor: '#1C1A43',
            border: '0.2px solid #252262',
            boxShadow: '0px 0px 60px 0px #635BFF4D',
        },
        spotlight: '/assets/spotlight5.png',
        tags: [{
                id: 1,
                name: 'React.js',
                path: '/assets/react.svg',
            },
            {
                id: 2,
                name: 'TailwindCSS',
                path: 'assets/tailwindcss.png',
            },
            {
                id: 3,
                name: 'TypeScript',
                path: '/assets/typescript.png',
            },
            {
                id: 4,
                name: 'Framer Motion',
                path: '/assets/framer.png',
            },
        ],
    },
    // {
    //     title: 'NINAuth',
    //     desc: ' NINAuth Enhance your privacy with outperforming authentication.',
    //     subdesc: 'Built with React.js, NINAuth can be used for secure identification and digital signatures with thousands of companies and authorities. This gives you complete visibility over your privacy and enhances your security.',
    //     href: 'https://ninauth.nimc.gov.ng/',
    //     texture: '/textures/project/Home _ NINAuth - Secure Digital Identity Authentication - Google Chrome 2025-10-21 00-42-12.mp4',
    //     logo: '/assets/project-logo5.png',
    //     logoStyle: {
    //         backgroundColor: '#1C1A43',
    //         border: '0.2px solid #252262',
    //         boxShadow: '0px 0px 60px 0px #635BFF4D',
    //     },
    //     spotlight: '/assets/spotlight5.png',
    //     tags: [{
    //             id: 1,
    //             name: 'React.js',
    //             path: '/assets/react.svg',
    //         },
    //         {
    //             id: 2,
    //             name: 'TailwindCSS',
    //             path: 'assets/tailwindcss.png',
    //         },
    //         {
    //             id: 3,
    //             name: 'TypeScript',
    //             path: '/assets/typescript.png',
    //         },
    //         {
    //             id: 4,
    //             name: 'Framer Motion',
    //             path: '/assets/framer.png',
    //         },
    //     ],
    // },
];

export const calculateSizes = (isSmall, isMobile, isTablet) => {
    return {
        deskScale: isSmall ? 0.05 : isMobile ? 0.06 : 0.065,
        deskPosition: isMobile ? [0.5, -4.5, 0] : [0.25, -5.5, 0],
        cubePosition: isSmall ? [4, -5, 0] : isMobile ? [5, -5, 0] : isTablet ? [5, -5, 0] : [9, -5.5, 0],
        reactLogoPosition: isSmall ? [3, 4, 0] : isMobile ? [5, 4, 0] : isTablet ? [5, 4, 0] : [12, 3, 0],
        ringPosition: isSmall ? [-5, 7, 0] : isMobile ? [-10, 10, 0] : isTablet ? [-12, 10, 0] : [-24, 10, 0],
        targetPosition: isSmall ? [-5, -10, -10] : isMobile ? [-9, -10, -10] : isTablet ? [-11, -7, -10] : [-13, -13, -10],
    };
};

export const workExperiences = [{
        id: 1,
        name: 'Muni',
        pos: 'Frontend Developer',
        duration: '2024 - 2024',
        title: " Muni is a groundbreaking Software-as-a-Service application that empowers users to monitor all their assets in a single app using AI technology. With features like AI-driven image editing, a payments system, and a credits-based model..",
        icon: '	https://munii.finance/_next/static/media/logo.114aa67b.svg',
        animation: 'victory',
    },
    {
        id: 2,
        name: 'Spatialnode',
        pos: 'Junior Frontend Developer',
        duration: '2023 - 2024',
        title: "Spatialnode is my collaborativeSpatialnode is the one-stop community for top-rated professionals, to showcase their works, discover opportunities and get inspired daily by the possibilities of geospatial technology design platform of choice. I utilize it to work seamlessly with team members and clients, facilitating real-time feedback and design iterations. Its cloud-based.",
        icon: '/assets/spatialnode.svg',
        animation: 'clapping',
    },
    {
        id: 3,
        name: 'Connectionskillz',
        pos: 'Junior Web Developer(internship)',
        duration: '2019 - 2020',
        title: "Connectionskillz helps me keep my projects organized. I use it for project management, task tracking, and as a central hub for documentation, ensuring that everything from design notes to.",
        icon: '/assets/notion.svg',
        animation: 'salute',
    },
];