export const navLinks = [{
        id: 1,
        name: 'Home',
        href: '#home',
    },
    {
        id: 2,
        name: 'About',
        href: '#about',
    },
    {
        id: 3,
        name: 'Work',
        href: '#work',
    },
    {
        id: 4,
        name: 'Contact',
        href: 'https://happy-birthday-diamond-mine.vercel.app/',
    },
];

export const clientReviews = [{
        id: 1,
        name: 'AbdulBait Adesiji',
        position: 'Product Designer • UX Researcher',
        img: 'assets/Screenshot_20241125-100937.png',
        review: 'He brings a rare mix of product thinking and engineering execution. The experience was smooth, thoughtful, and outcome-focused from concept to launch.',
    },
];

export const myProjects = [
    {
        title: 'RegaL Flowers',
        platform: 'Web / Full-stack',
        role: 'Ecommerce platform · storefront · payments',
        desc: 'High-converting ecommerce experience for a same-day delivery flower brand across Lagos and Abuja.',
        subdesc: 'Built with Next.js, Node.js, MongoDB, Stripe, Firebase, and Tailwind CSS to support a scalable online storefront and customer-first shopping experience.',
        href: 'https://www.regalflowers.com.ng/',
        texture: '/textures/project/Regal Flowers _ Same Day Flower Delivery Shop in Lagos and Abuja, Nigeria - Google Chrome 2024-11-25 09-01-26.mp4',
        logo: '/assets/project-logo1.png',
        logoStyle: {
            backgroundColor: '#2A1816',
            border: '0.2px solid #36201D',
            boxShadow: '0px 0px 60px 0px #AA3C304D',
        },
        spotlight: '/assets/spotlight1.png',
        tags: [
            { id: 1, name: 'React.js', path: '/assets/react.svg' },
            { id: 2, name: 'TailwindCSS', path: 'assets/tailwindcss.png' },
            { id: 3, name: 'TypeScript', path: '/assets/typescript.png' },
            { id: 4, name: 'Node.js' },
        ],
    },
    {
        title: 'MedHealthCatalyst',
        platform: 'Web / Full-stack',
        role: 'Healthcare platform · workflows · notifications',
        desc: 'Healthcare management platform designed to streamline patient workflows, scheduling, and digital operations.',
        subdesc: 'Built for efficient care delivery and data handling with Next.js, Appwrite, Twilio, and modern form-driven UX patterns for clinical operations.',
        href: 'https://med-health-catalyst-bpd5.vercel.app/',
        texture: '/textures/project/MedHealthCatalyst - Google Chrome 2024-11-25 08-37-26.mp4',
        logo: '/assets/project-logo3.png',
        logoStyle: {
            backgroundColor: '#60f5a1',
            background: 'linear-gradient(0deg, #60F5A150, #60F5A150), linear-gradient(180deg, rgba(255, 255, 255, 0.9) 0%, rgba(208, 213, 221, 0.8) 100%)',
            border: '0.2px solid rgba(208, 213, 221, 1)',
            boxShadow: '0px 0px 60px 0px rgba(35, 131, 96, 0.3)',
        },
        spotlight: '/assets/spotlight3.png',
        tags: [
            { id: 1, name: 'Next.js' },
            { id: 2, name: 'TailwindCSS', path: 'assets/tailwindcss.png' },
            { id: 3, name: 'Appwrite' },
            { id: 4, name: 'Twilio' },
        ],
    },
    {
        title: 'Connectinskillz',
        platform: 'Web / Platform',
        role: 'Learning platform · dashboards · collaboration',
        desc: 'Learning platform connecting students, mentors, and administrators through a clean, engagement-focused experience.',
        subdesc: 'Built to support learning journeys, real-time collaboration, assignments, and modern LMS flows with a scalable frontend architecture.',
        href: 'https://www.connectinskillz.org/',
        texture: '/textures/project/Home _ ConnectinSkillz - Google Chrome 2024-11-25 09-17-39.mp4',
        logo: '/assets/project-logo4.png',
        logoStyle: {
            backgroundColor: '#0E1F38',
            border: '0.2px solid #0E2D58',
            boxShadow: '0px 0px 60px 0px #2F67B64D',
        },
        spotlight: '/assets/spotlight4.png',
        tags: [
            { id: 1, name: 'React.js', path: '/assets/react.svg' },
            { id: 2, name: 'Next.js' },
            { id: 3, name: 'TypeScript', path: '/assets/typescript.png' },
            { id: 4, name: 'UI Systems' },
        ],
    },
    {
        title: 'Tweakrr',
        platform: 'Web / Product',
        role: 'AI-assisted workflow · responsive product UX',
        desc: 'AI-assisted academic workflow platform built for productivity, citations, and knowledge operations.',
        subdesc: 'Responsive product experience focused on seamless workflows, polished UX, and reliable integrations for automation and generation features.',
        href: 'https://www.tweakrr.com/',
        texture: '/textures/project/Tweakrr - Google Chrome 2025-08-16 18-29-16.mp4',
        logo: '/assets/project-logo5.png',
        logoStyle: {
            backgroundColor: '#1C1A43',
            border: '0.2px solid #252262',
            boxShadow: '0px 0px 60px 0px #635BFF4D',
        },
        spotlight: '/assets/spotlight5.png',
        tags: [
            { id: 1, name: 'Next.js' },
            { id: 2, name: 'TailwindCSS', path: 'assets/tailwindcss.png' },
            { id: 3, name: 'React Native' },
            { id: 4, name: 'Product UX' },
        ],
    },
    {
        title: 'Celebration Websites',
        platform: 'Custom / Interactive Web',
        role: 'Birthdays · appreciation · surprise experiences',
        desc: 'Personalized websites and interactive digital experiences for birthdays, anniversaries, celebrations, and meaningful surprises.',
        subdesc: 'I create memorable one-off experiences with custom storytelling, photos, music, animations, heartfelt messages, and responsive layouts that feel special on every device. Perfect for birthday tributes, appreciation pages, proposal surprises, and event moments.',
        href: '#contact',
        texture: '/textures/project/birthday.mp4',
        logo: '/assets/project-logo2.png',
        logoStyle: {
            backgroundColor: '#2a1c2c',
            border: '0.2px solid #6b3d6f',
            boxShadow: '0px 0px 60px 0px #d88be84d',
        },
        spotlight: '/assets/spotlight2.png',
        tags: [
            { id: 1, name: 'Interactive UI' },
            { id: 2, name: 'Animations' },
            { id: 3, name: 'Responsive Web' },
            { id: 4, name: 'Storytelling' },
        ],
    },
    {
        title: 'Truxpense',
        platform: 'Mobile + Web',
        role: 'React Native app · expense tracking · financial insights',
        desc: 'Mobile expense management experience designed for fast capture, clear spending awareness, and everyday financial control.',
        subdesc: 'I shaped the product around small-screen interactions, readable insights, reusable React Native components, and responsive companion web flows.',
        href: 'https://truxpense.com/',
        texture: '/textures/project/truxpense.mp4',
        logo: '/assets/project-logo5.png',
        logoStyle: {
            backgroundColor: '#18251d',
            border: '0.2px solid #304936',
            boxShadow: '0px 0px 60px 0px #88c9994d',
        },
        spotlight: '/assets/spotlight5.png',
        tags: [
            { id: 1, name: 'React Native' },
            { id: 2, name: 'TypeScript', path: '/assets/typescript.png' },
            { id: 3, name: 'Redux Toolkit' },
            { id: 4, name: 'Mobile UX' },
        ],
    },
    {
        title: 'Rekrutklin',
        platform: 'Web + Mobile',
        role: 'Recruitment platform · candidate app flows · employer tools',
        desc: 'Recruitment marketplace connecting employers and candidates through focused web and mobile journeys.',
        subdesc: 'I built responsive product flows for job discovery, candidate engagement, and employer workflows, with mobile-first interaction patterns that support real usage on the go.',
        href: 'https://rekrutklin.com/',
        texture: '/textures/project/rekrutklin.mp4',
        logo: '/assets/LOGO.svg',
        logoStyle: {
            backgroundColor: '#1C1A43',
            border: '0.2px solid #252262',
            boxShadow: '0px 0px 60px 0px #635BFF4D',
        },
        spotlight: '/assets/spotlight5.png',
        tags: [
            { id: 1, name: 'React.js', path: '/assets/react.svg' },
            { id: 2, name: 'Next.js' },
            { id: 3, name: 'React Native' },
            { id: 4, name: 'Mobile UX' },
        ],
    },
    {
        title: 'Nablr',
        platform: 'Mobile + Web',
        role: 'React Native experience · discovery · engagement',
        desc: 'Cross-platform product experience focused on discovery, engagement, and repeat usage across web and mobile.',
        subdesc: 'The interface is designed around touch-friendly navigation, reusable mobile components, performant screens, and consistent product behavior across devices.',
        href: 'https://nablr.com/',
        texture: '/textures/project/nablr.mp4',
        logo: '/assets/project-logo5.png',
        logoStyle: {
            backgroundColor: '#1C1A43',
            border: '0.2px solid #252262',
            boxShadow: '0px 0px 60px 0px #635BFF4D',
        },
        spotlight: '/assets/spotlight5.png',
        tags: [
            { id: 1, name: 'React Native' },
            { id: 2, name: 'TailwindCSS', path: 'assets/tailwindcss.png' },
            { id: 3, name: 'TypeScript', path: '/assets/typescript.png' },
            { id: 4, name: 'Responsive UI' },
        ],
    },
    {
        title: 'Spatialnode',
        platform: 'Web / Community',
        role: 'Geospatial community · profiles · discovery',
        desc: 'Collaboration-first platform built for geospatial discovery, professional visibility, and community engagement.',
        subdesc: 'Crafted around clear information architecture, smooth user journeys, and scalable frontend flows that support growth and trust.',
        href: 'https://www.spatialnode.net/',
        texture: '/textures/project/spatialnode.mp4',
        logo: '/assets/project-logo5.png',
        logoStyle: {
            backgroundColor: '#1C1A43',
            border: '0.2px solid #252262',
            boxShadow: '0px 0px 60px 0px #635BFF4D',
        },
        spotlight: '/assets/spotlight5.png',
        tags: [
            { id: 1, name: 'React.js', path: '/assets/react.svg' },
            { id: 2, name: 'Next.js' },
            { id: 3, name: 'UX Design' },
            { id: 4, name: 'Scalable UI' },
        ],
    },
    {
        title: 'NINAuth',
        platform: 'Web / Security',
        role: 'Identity platform · authentication · verification',
        desc: 'Secure identity and authentication experience focused on privacy, trust, and digital verification.',
        subdesc: 'Built for secure workflows, clean UX, and enterprise-ready frontend architecture with a strong emphasis on reliability and clarity.',
        href: 'https://ninauth.nimc.gov.ng/',
        texture: '/textures/project/Home _ NINAuth - Secure Digital Identity Authentication - Google Chrome 2025-10-21 00-42-12.mp4',
        logo: '/assets/project-logo5.png',
        logoStyle: {
            backgroundColor: '#1C1A43',
            border: '0.2px solid #252262',
            boxShadow: '0px 0px 60px 0px #635BFF4D',
        },
        spotlight: '/assets/spotlight5.png',
        tags: [
            { id: 1, name: 'React.js', path: '/assets/react.svg' },
            { id: 2, name: 'Security' },
            { id: 3, name: 'TypeScript', path: '/assets/typescript.png' },
            { id: 4, name: 'Design Systems' },
        ],
    },
];

export const calculateSizes = (isSmall, isMobile, isTablet) => {
    return {
        deskScale: isSmall ? 0.05 : isMobile ? 0.06 : 0.065,
        deskPosition: isMobile ? [0.5, -4.5, 0] : [0.25, -5.5, 0],
        cubePosition: isSmall ? [4, -5, 0] : isMobile ? [5, -5, 0] : isTablet ? [5, -5, 0] : [9, -5.5, 0],
        reactLogoPosition: isSmall ? [3, 4, 0] : isMobile ? [5, 4, 0] : isTablet ? [5, 4, 0] : [12, 3, 0],
        ringPosition: isSmall ? [-5, 7, 0] : isMobile ? [-10, 10, 0] : isTablet ? [-12, 10, 0] : [-24, 10, 0],
        targetPosition: isSmall ? [-5, -10, -10] : isMobile ? [-9, -10, -10] : isTablet ? [-11, -7, -10] : [-13, -13, -10],
    };
};

export const workExperiences = [{
        id: 1,
        name: 'Muni',
        pos: 'Frontend Developer',
        duration: '2024 - 2024',
        title: 'SaaS banking platform experience built for asset visibility, finance workflows, and modern customer engagement.',
        icon: 'https://munii.finance/_next/static/media/logo.114aa67b.svg',
        animation: 'victory',
    },
    {
        id: 2,
        name: 'Spatialnode',
        pos: 'Frontend Developer',
        duration: '2023 - 2024',
        title: 'Community-driven geospatial platform focused on showcasing expertise, discovery, and growth opportunities.',
        icon: '/assets/spatialnode.svg',
        animation: 'clapping',
    },
    {
        id: 3,
        name: 'Connectionskillz',
        pos: 'Junior Web Developer',
        duration: '2019 - 2020',
        title: 'Learning and project coordination platform designed to streamline team workflows and student engagement.',
        icon: '/assets/notion.svg',
        animation: 'salute',
    },
];
